name: Rust - build & test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Get Package
        run: apt-get install libopenblas-base libopenblas-dev
         
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
